// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import Script from "next/script";
import "./globals.css";

// Fonte redonda e moderna
const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Aurance - Controlo Financeiro Inteligente",
  description: "Organize as suas finanças de forma simples, visual e eficiente com Aurance",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${nunito.variable} font-sans antialiased`}
        style={{ fontFamily: 'var(--font-nunito)' }}
      >
        {children}
      </body>
    </html>
  );
}
